[project]
name = "backends"
version = "0.1.0"
description = ""
readme = "README.md"
requires-python = ">=3.12"

dependencies = [
    "fastapi>=0.110",
    "uvicorn[standard]>=0.30",
    "pydantic>=2.7",
    "python-dotenv>=1.0",
    "requests>=2.33.1",
    "httpx>=0.28.1",
    "loguru>=0.7.3",
]

[project.optional-dependencies]
dev = [
    "ruff>=0.15.12"
]

[dependency-groups]
dev = [
    "ruff>=0.15.12",
]
